# Generated by Django 4.0.4 on 2023-04-09 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
